version: '3.1'

services:
  db:
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${APP_DB}

  web:
    image: petal-app
    build: .
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}

    environment:
      APP_PORT: ${APP_PORT}
      APP_HOSTNAME: ${APP_HOSTNAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      APP_DB: ${APP_DB}

    depends_on:
      - db